stages:
  - "Test"

language: node_js
node_js:
  - "14.17.6"
cache: npm

install:
  - npm i --prefix backend/
  - npm i --prefix frontend/

jobs:
  include:
    - stage: "Test"
      name: "Lint-backend"
      script: cd backend && npm run lint
    - stage: "Test"
      name: "Test-backend"
      script: cd backend && npm run test

    - stage: "Test"
      name: "Lint-frontend"
      script: cd frontend && npm run lint
    - stage: "Test"
      name: "Test-frontend"
      script: cd frontend && npm run test
