version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    restart: always
    ports:
      - 1433:1433
    volumes:
      - ./storage/database/data:/data
    environment:
      - MSSQL_SA_PASSWORD=Admin123
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y

  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - ./storage/cachingSystem/data:/data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis

  # uncomment if you want to use adminer
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8181:8080
