version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    restart: always
    user: root
    ports:
      - 1433:1433
    volumes:
      - ./storage/database/data:/var/opt/mssql/data
    environment:
      - MSSQL_SA_PASSWORD=Admin123
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 10s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Admin123 -d master -Q 'CREATE DATABASE campaign_keeper' && sleep infinity"

  redis:
    image: redis:6.2.6
    restart: always
    volumes:
      - ./storage/cachingSystem/data:/data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis

  # uncomment if you want to use adminer
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8181:8080
