insert into "schema_instance_metadata" (id, object_id, type, value, sequence_number, field_name)
values  (38, 8, N'string', N'Ellie Sattler', 0, N'Name'),
        (39, 8, N'id', N'7', 0, N'Affiliations'),
        (40, 8, N'string', N'Archeologists, Biologists', 0, N'Occupation'),
        (41, 8, N'string', N'Is fascinated about living dinosaurs and want to  help them.', 0, N'Description'),
        (42, 7, N'string', N'Alan Grant', 0, N'Name'),
        (43, 7, N'id', N'8', 0, N'Affiliations'),
        (44, 7, N'string', N'Archeologist', 0, N'Occupation'),
        (45, 7, N'string', N'Sceptic passionated about dinosaurs, but likes them more rock dead. ', 0, N'Description'),
        (46, 9, N'string', N'Ian Malcolm', 0, N'Name'),
        (47, 9, N'string', N'None', 0, N'Affiliations'),
        (48, 9, N'string', N'Mathematise ', 0, N'Occupation'),
        (49, 9, N'string', N'CHAOS.', 0, N'Description'),
        (50, 10, N'string', N'John Hammond', 0, N'Name'),
        (51, 10, N'string', N'Jurassic Park crew', 0, N'Affiliations'),
        (52, 10, N'string', N'Rich guy', 0, N'Occupation'),
        (53, 10, N'string', N'Big vision, heart, lack of common sense. Was there when every dinosaur was born.', 0, N'Description'),
        (54, 11, N'string', N'Tyrannosaurus Rex', 0, N'Name'),
        (55, 11, N'id', N'10', 0, N'Affiliations'),
        (56, 11, N'string', N'Eats people', 0, N'Occupation'),
        (57, 11, N'string', N'Big, hungry hunter.', 0, N'Description'),
        (58, 12, N'string', N'The island where ', 0, N'Description'),
        (59, 12, N'id', N'10', 1, N'Description'),
        (60, 12, N'string', N' decided to make his dinosaur park.', 2, N'Description'),
        (61, 12, N'id', N'11', 0, N'Residents'),
        (62, 13, N'string', N'The famous gate to the Jurassic Park', 0, N'Description'),
        (63, 13, N'string', N' ', 0, N'Residents'),
        (64, 14, N'string', N'Base where tourists  can rest and eat.', 0, N'Description'),
        (65, 14, N'string', N'Children', 0, N'Residents'),
        (66, 15, N'string', N'Famous Jeep tour. Fully automated. Lacks dinosaurs.', 0, N'Description'),
        (67, 15, N'string', N'None (unfortunately)', 0, N'Residents'),
        (72, 17, N'string', N'Sample location', 0, N'Location'),
        (73, 17, N'string', N'Sample county', 0, N'Country'),
        (74, 17, N'string', N'Sample population', 0, N'Population'),
        (75, 17, N'string', N'Sample powerful ruler', 0, N'Ruler'),
        (76, 17, N'string', N'Some sample points of interest', 0, N'Points of interest'),
        (77, 18, N'string', N'George', 0, N'Name'),
        (78, 18, N'string', N'Stefano', 0, N'Surname'),
        (79, 18, N'string', N'32', 0, N'Age'),
        (80, 18, N'string', N'Italian cook', 0, N'Occupation'),
        (81, 18, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (82, 18, N'string', N'Quiet and polite person', 0, N'Character'),
        (232, 46, N'string', N'George', 0, N'Name'),
        (233, 46, N'string', N'Stefano', 0, N'Surname'),
        (234, 46, N'string', N'32', 0, N'Age'),
        (235, 46, N'string', N'Italian cook', 0, N'Occupation'),
        (236, 46, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (237, 46, N'string', N'Quiet and polite person', 0, N'Character'),
        (238, 47, N'string', N'Sample location', 0, N'Location'),
        (239, 47, N'string', N'Sample county', 0, N'Country'),
        (240, 47, N'string', N'Sample population', 0, N'Population'),
        (241, 47, N'string', N'Sample powerful ruler', 0, N'Ruler'),
        (242, 47, N'string', N'Some sample points of interest', 0, N'Points of interest'),
        (260, 37, N'string', N'George', 0, N'Name'),
        (261, 37, N'string', N'Stefano', 0, N'Surname'),
        (262, 37, N'string', N'32', 0, N'Age'),
        (263, 37, N'string', N'Italian cook', 0, N'Occupation'),
        (264, 37, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (265, 37, N'string', N'Quiet and polite person', 0, N'Character'),
        (266, 37, N'id', N'37', 1, N'Character'),
        (267, 37, N'string', N' asddas', 2, N'Character'),
        (268, 48, N'string', N'George', 0, N'Name'),
        (269, 48, N'string', N'Stefano', 0, N'Surname'),
        (270, 48, N'string', N'32', 0, N'Age'),
        (271, 48, N'string', N'Italian cook', 0, N'Occupation'),
        (272, 48, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (273, 48, N'string', N'Quiet and polite person', 0, N'Character'),
        (274, 49, N'string', N'Sample location', 0, N'Location'),
        (275, 49, N'string', N'Sample county', 0, N'Country'),
        (276, 49, N'string', N'Sample population', 0, N'Population'),
        (277, 49, N'string', N'Sample powerful ruler', 0, N'Ruler'),
        (278, 49, N'string', N'Some sample points of interest', 0, N'Points of interest'),
        (294, 16, N'string', N'Samuel Jackson', 0, N'Name'),
        (295, 16, N'id', N'10', 0, N'Affiliations'),
        (296, 16, N'string', N'Doctor with a cigarette', 0, N'Occupation'),
        (297, 16, N'string', N'With both eyes and arms. At least for now.', 0, N'Description'),
        (359, 64, N'string', N'Sample location', 0, N'Location'),
        (360, 64, N'string', N'Sample county', 0, N'Country'),
        (361, 64, N'string', N'Sample population', 0, N'Population'),
        (362, 64, N'string', N'Sample powerful ruler', 0, N'Ruler'),
        (363, 64, N'string', N'Some sample points of interest', 0, N'Points of interest'),
        (364, 65, N'string', N'George', 0, N'Name'),
        (365, 65, N'string', N'Stefano', 0, N'Surname'),
        (366, 65, N'string', N'32', 0, N'Age'),
        (367, 65, N'string', N'Italian cook', 0, N'Occupation'),
        (368, 65, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (369, 65, N'string', N'Quiet and polite person', 0, N'Character'),
        (380, 68, N'string', N'', 0, N'Name'),
        (381, 68, N'string', N'', 0, N'Surname'),
        (382, 68, N'string', N'', 0, N'Degree'),
        (383, 68, N'string', N'', 0, N'Courses'),
        (384, 68, N'string', N'', 0, N'Salary'),
        (385, 67, N'string', N'Shephard', 0, N'Name'),
        (386, 67, N'string', N'Shephard', 0, N'Surname'),
        (387, 67, N'string', N'Shephard', 0, N'Degree'),
        (388, 67, N'string', N'Shephard', 0, N'Courses'),
        (389, 67, N'string', N'Shephard', 0, N'Salary'),
        (390, 69, N'string', N'', 0, N'Name'),
        (391, 69, N'string', N'', 0, N'Surname'),
        (392, 69, N'string', N'', 0, N'Degree'),
        (393, 69, N'string', N'', 0, N'Courses'),
        (394, 69, N'string', N'', 0, N'Salary'),
        (395, 70, N'string', N'', 0, N'Name'),
        (396, 70, N'string', N'', 0, N'Surname'),
        (397, 70, N'string', N'', 0, N'Degree'),
        (398, 70, N'string', N'', 0, N'Courses'),
        (399, 70, N'string', N'', 0, N'Salary'),
        (400, 71, N'string', N'', 0, N'Name'),
        (401, 71, N'string', N'', 0, N'Surname'),
        (402, 71, N'string', N'', 0, N'Degree'),
        (403, 71, N'string', N'', 0, N'Courses'),
        (404, 71, N'string', N'', 0, N'Salary'),
        (405, 72, N'string', N'', 0, N'Name'),
        (406, 72, N'string', N'', 0, N'Surname'),
        (407, 72, N'string', N'', 0, N'Degree'),
        (408, 72, N'string', N'', 0, N'Courses'),
        (409, 72, N'string', N'', 0, N'Salary'),
        (410, 73, N'string', N'Algebra 1', 0, N'Name'),
        (411, 73, N'string', N'1st', 0, N'Year'),
        (412, 74, N'string', N'Algebra 2', 0, N'Name'),
        (413, 74, N'string', N'2nd', 0, N'Year'),
        (414, 66, N'string', N'John', 0, N'Name'),
        (415, 66, N'string', N'Smith', 0, N'Surname'),
        (416, 66, N'string', N'PhD', 0, N'Degree'),
        (417, 66, N'id', N'73', 0, N'Courses'),
        (418, 66, N'string', N', ', 1, N'Courses'),
        (419, 66, N'id', N'74', 2, N'Courses'),
        (420, 66, N'string', N', Graphic Design 1 (substitute for ', 3, N'Courses'),
        (421, 66, N'id', N'70', 4, N'Courses'),
        (422, 66, N'string', N')', 5, N'Courses'),
        (423, 66, N'string', N'60 000$', 0, N'Salary'),
        (424, 76, N'string', N'Antilus ', 0, N'Name'),
        (425, 76, N'string', N'Gaius', 0, N'Surname'),
        (426, 76, N'string', N'36', 0, N'Age'),
        (427, 76, N'string', N'Captain of Imperial Guard', 0, N'Occupation'),
        (428, 76, N'string', N'Tall, balding', 0, N'Description'),
        (429, 76, N'string', N'', 0, N'Character'),
        (452, 81, N'string', N'Sample location', 0, N'Location'),
        (453, 81, N'string', N'Sample county', 0, N'Country'),
        (454, 81, N'string', N'Sample population', 0, N'Population'),
        (455, 81, N'string', N'Sample powerful ruler', 0, N'Ruler'),
        (456, 81, N'string', N'Some sample points of interest', 0, N'Points of interest'),
        (457, 82, N'string', N'George', 0, N'Name'),
        (458, 82, N'string', N'Stefano', 0, N'Surname'),
        (459, 82, N'string', N'32', 0, N'Age'),
        (460, 82, N'string', N'Italian cook', 0, N'Occupation'),
        (461, 82, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (462, 82, N'string', N'Quiet and polite person', 0, N'Character'),
        (505, 86, N'string', N'Aden', 0, N'Name'),
        (506, 86, N'string', N'Unknown', 0, N'Surname'),
        (507, 86, N'string', N'Michał', 0, N'Player'),
        (508, 86, N'string', N'Human (Reborn)', 0, N'Race'),
        (509, 86, N'string', N'Fighter (Battlemaster) 10', 0, N'Class'),
        (510, 86, N'string', N'Kingdom of Cormyr', 0, N'Affilation'),
        (511, 86, N'string', N'Secondary character: veteran of Abyssal Crusade who got lost in Avernus and was cursed to wander its wastes for eternity. Plotline: none as of yet', 0, N'Notes'),
        (519, 88, N'string', N'Leonardo', 0, N'Name'),
        (520, 88, N'string', N'', 0, N'Surname'),
        (521, 88, N'string', N'Michał', 0, N'Player'),
        (522, 88, N'string', N'Kobold', 0, N'Race'),
        (523, 88, N'string', N'Wizard (Order of Scribes) 7', 0, N'Class'),
        (524, 88, N'string', N'Himself', 0, N'Affilation'),
        (525, 88, N'string', N'Primary character for Michał until start of Act II, then removed from game due to Michał''s temporary departure. No longer used.', 0, N'Notes'),
        (533, 87, N'string', N'Belos', 0, N'Name'),
        (534, 87, N'string', N'Blackbane', 0, N'Surname'),
        (535, 87, N'string', N'Przemek', 0, N'Player'),
        (536, 87, N'string', N'Reborn (Tabaxi)', 0, N'Race'),
        (537, 87, N'string', N'Ranger (Gloomstalker) 8', 0, N'Class'),
        (538, 87, N'string', N'Olanthius', 0, N'Affilation'),
        (539, 87, N'string', N'Secondary character: used in the Pit of Shummrath subplot as temporary replacement for Teonto. No longer in use.', 0, N'Notes'),
        (561, 90, N'string', N'Zariel', 0, N'Name'),
        (562, 90, N'string', N'Fiend (ex Celestial)', 0, N'Race'),
        (563, 90, N'string', N'Archduchess of Avernus', 0, N'Position'),
        (564, 90, N'string', N'Patron for players'' team, formerly BBEG', 0, N'Role in campaign'),
        (565, 90, N'string', N'Responsible for dragging Elturel into Avernus', 0, N'Notes'),
        (566, 91, N'string', N'Bahamut', 0, N'Name'),
        (567, 91, N'string', N'Lesser deity (dragon)', 0, N'Race'),
        (568, 91, N'string', N'God of Metallic Dragons, Patron of Elturel', 0, N'Position'),
        (569, 91, N'string', N'Players'' team patron', 0, N'Role in campaign'),
        (570, 91, N'string', N'', 0, N'Notes'),
        (571, 92, N'string', N'Mahdi', 0, N'Name'),
        (572, 92, N'string', N'Rakshasa', 0, N'Race'),
        (573, 92, N'string', N'Owner of Wandering Emporium ', 0, N'Position'),
        (574, 92, N'string', N'Merchant, questgiver', 0, N'Role in campaign'),
        (575, 92, N'string', N'Commissioned players'' team to find his daughter', 0, N'Notes'),
        (576, 93, N'string', N'Eliza', 0, N'Name'),
        (577, 93, N'string', N'Celestial', 0, N'Race'),
        (578, 93, N'string', N'Chief investigator at Zariel''s court', 0, N'Position'),
        (579, 93, N'string', N'Questgiver, helper, secondary character', 0, N'Role in campaign'),
        (580, 93, N'string', N'Has been tasked with overseeing Teonto after his ascension to Half-Erinyes', 0, N'Notes'),
        (581, 94, N'string', N'Smiler', 0, N'Name'),
        (582, 94, N'string', N'Eladrin', 0, N'Race'),
        (583, 94, N'string', N'Avernus'' Wastes Warlord', 0, N'Position'),
        (584, 94, N'string', N'Questgiver, potential enemy', 0, N'Role in campaign'),
        (585, 94, N'string', N'Slick, insane and treacherous ', 0, N'Notes'),
        (586, 95, N'string', N'Kirkendolt', 0, N'Name'),
        (587, 95, N'string', N'Fiend', 0, N'Race'),
        (588, 95, N'string', N'Teonto''s Sidekick', 0, N'Position'),
        (589, 95, N'string', N'Sidekick, warrior for hire, comedic relief', 0, N'Role in campaign'),
        (590, 95, N'string', N'Tries to be good', 0, N'Notes'),
        (596, 97, N'string', N'Ludovig', 0, N'Name'),
        (597, 97, N'string', N'Fiend (Pit Fiend)', 0, N'Race'),
        (598, 97, N'string', N'Infernal Legion''s Warmaster, leader of Army Group East', 0, N'Position'),
        (599, 97, N'string', N'Questgiver, helper, potential enemy', 0, N'Role in campaign'),
        (600, 97, N'string', N'Wants to obtain Heart of Agathys for himself despite being an infernal patriot', 0, N'Notes'),
        (613, 99, N'string', N'Crosier of Asgorath', 0, N'Name'),
        (614, 99, N'string', N'Artefact, legendary', 0, N'Rarity'),
        (615, 99, N'id', N'85', 0, N'Owner'),
        (616, 99, N'string', N'Regalia of the high priests from the ages long forgotten. Created from the unknown metal, this crosier shines with a divine glow, shedding warm light upon its surroundings. The colours in its touch seem deeper, the edges feel sharper and any sound feels as if it echoes upon unseen crests. The staff seems incredibly solid in touch, even though it seems ephemeral in appearance. Slight rights, resembling scales cover its hilt up to the five-headed dragon, wrapped around the golden orb. Amber sphere sits between them as if cradled in a motherly embrace, protected by the platinum dragon above. In its misty interior, it seems, as if the shadow of the ancient serpent is stirring; a hope, yet to be fulfilled.', 0, N'Description'),
        (617, 100, N'string', N'Azureblood', 0, N'Name'),
        (618, 100, N'string', N'Artefact, legendary', 0, N'Rarity'),
        (619, 100, N'id', N'84', 0, N'Owner'),
        (620, 100, N'string', N'Hidden in the depths of the Moon Shard,  Azureblood shines like a piece of night sky filled with stars. A piece of eerie magic, long forgotten by any kind. A forgery, a masterpiece, a monstrosity. The hideous attempt of the fallen Netheril, to recreate the work of their rivals: Gith Empire. This weapon is anathema to any Silver Sword in existence, even though it shares much of their powers, or even surpasses them too much extent, but at a cost. Alien sentience stirs in the blade, sipping on the life of the wielder and that slain, obliterating mind and body in its distorted pursuit of good.', 0, N'Description'),
        (621, 101, N'string', N'Gladius Daemones', 0, N'Name'),
        (622, 101, N'id', N'90', 0, N'Ruler/owner'),
        (623, 101, N'string', N'Flying fortress', 0, N'Type'),
        (624, 101, N'string', N'An enormous flying fortress which soars through skies of Avernus. It serves as headquarters for its rulers and garrison for her personal legions. ', 0, N'Description'),
        (625, 102, N'string', N'Wandering Emporium', 0, N'Name'),
        (626, 102, N'id', N'92', 0, N'Ruler/owner'),
        (627, 102, N'string', N'Marketplace', 0, N'Type'),
        (628, 102, N'string', N'An enormous mobile emporium moving through Avernus catering to all of its citizens. It can operate thanks to deal its owner struck with ', 0, N'Description'),
        (629, 102, N'id', N'90', 1, N'Description'),
        (630, 102, N'string', N'.', 2, N'Description'),
        (639, 104, N'string', N'Army Group East Camp', 0, N'Name'),
        (640, 104, N'id', N'97', 0, N'Ruler/owner'),
        (641, 104, N'string', N'Infernal army camp, marketplace', 0, N'Type'),
        (642, 104, N'string', N'Enormous military complex housing hundreds of thousands of devils with all necessary service to support infernal legions.', 0, N'Description'),
        (647, 103, N'string', N'Avernus Wastes', 0, N'Name'),
        (648, 103, N'string', N'Various warlords', 0, N'Ruler/owner'),
        (649, 103, N'string', N'', 0, N'Type'),
        (650, 103, N'string', N'Almost entirety of Avernus is covered in vast wastelands, ruled by warlords and their power of brute strength. ', 0, N'Description'),
        (682, 84, N'string', N'Gisarathia (ex Gisarath)', 0, N'Name'),
        (683, 84, N'string', N'Varsh', 0, N'Surname'),
        (684, 84, N'string', N'Kuba (Senior)', 0, N'Player'),
        (685, 84, N'string', N'Half-Elf/Half-Gith (ex. Half-Drow/Half-Gith, ex Gith)', 0, N'Race'),
        (686, 84, N'string', N'Rogue (Soulknife) 6/Monk (Way of the Cobalt Soul) 5', 0, N'Class'),
        (687, 84, N'string', N'themselves', 0, N'Affilation'),
        (688, 84, N'string', N'Died during Siege of Fallen Fortress, reincarnated as Half-Drow/Half-Gith, died again, reincarnated as Half-Elf/Half-Gith. 
Plotline: Gith Empire Remnants', 0, N'Notes'),
        (689, 83, N'string', N'Teonto', 0, N'Name'),
        (690, 83, N'string', N'Lightscourge (ex Lightbringer)', 0, N'Surname'),
        (691, 83, N'string', N'Przemek', 0, N'Player'),
        (692, 83, N'string', N'Erinyes/Fallen Aasimar (ex Fallen Aasimar, ex Scourge Aasimar, ex Satyr)', 0, N'Race'),
        (693, 83, N'string', N'Paladin (Oath of Vengeance) 6/ Warlock (Hexblade) 5', 0, N'Class'),
        (694, 83, N'id', N'90', 0, N'Affilation'),
        (695, 83, N'string', N' (formerly Selune, Goddess of the Moon)', 1, N'Affilation'),
        (696, 83, N'string', N'Died during Skirmish at Stinky''s Breath Outpost, resurrected and bounded with infernal contract by Zariel three days later. 
Plotline: Erinyes Ascension Path', 0, N'Notes'),
        (697, 85, N'string', N'Rassvet', 0, N'Name'),
        (698, 85, N'string', N'', 0, N'Surname'),
        (699, 85, N'string', N'Kuba (Jr)', 0, N'Player'),
        (700, 85, N'string', N'Platinum Dragonborn (ex Gold Dragonborn)', 0, N'Race'),
        (701, 85, N'string', N'Druid (Circle of Wildfire) 11', 0, N'Class'),
        (702, 85, N'id', N'91', 0, N'Affilation'),
        (703, 85, N'string', N'Gradually transformed into Platinum Dragonborn by Bahamut as reward for his noble actions. 
Plotline: Ancient Draconic Gods', 0, N'Notes'),
        (704, 89, N'string', N'Pherria', 0, N'Name'),
        (705, 89, N'string', N'Arilies', 0, N'Surname'),
        (706, 89, N'string', N'Ola', 0, N'Player'),
        (707, 89, N'string', N'Dhampir', 0, N'Race'),
        (708, 89, N'string', N'Cleric (Twilight Domain) 9', 0, N'Class'),
        (709, 89, N'id', N'91', 0, N'Affilation'),
        (710, 89, N'string', N'Secondary character up to halfway through Act III when player left campaign due to personal issues. ', 0, N'Notes'),
        (711, 98, N'string', N'Erinyes Judgment', 0, N'Name'),
        (712, 98, N'string', N'Artefact, legendary', 0, N'Rarity'),
        (713, 98, N'id', N'83', 0, N'Owner'),
        (714, 98, N'string', N'Foul radiance emanates from the blade, aflame with the fiendish power, that became the soul of that weapon. A bloody hue spews from it, painting the surroundings in raw, tangible edges and sharp lines. Unnerving, muffled cries of the judged souls emanate from it as they succumb to the eternal torment, rightfully given to those, who oppose its wielder. The seemingly simple guard and pommel do not convey the true masterwork and craftsmanship poured into the weapon. An actual piece of craft, which couldn''t be made by any mortal smith carries the will of its wielder, even so sharp, as his wits and determination, to unveil the truth and pass the just judgment upon the sinners, even stronger as his ties to the infernal throne tighten. 

This blade truly became the armament of Erinyes in the making. One of many procured, to aid the infernal judge in her endeavour to pass the justice onto the wretched in the name of the Archduchess Zariel now fully became an extension of the will of her new servant, blessing him with profane powers of hell and the aid, of his sovereign. A powerful tool, and proof of his newfound faith and allegiance.', 0, N'Description'),
        (849, 119, N'string', N'QUARTERS', 0, N'Name'),
        (850, 119, N'string', N'Yes', 0, N'Is pressurised?'),
        (851, 119, N'string', N'Crew quarters: recreation and sleeping area', 0, N'Role'),
        (852, 119, N'string', N'1. ', 0, N'Rooms'),
        (853, 119, N'id', N'108', 1, N'Rooms'),
        (854, 119, N'string', N'''s bunk: a lanyard hanging on a wall hook, with a key card on it that authorises airlock use when plugged into the computer at her office in ', 2, N'Rooms'),
        (855, 119, N'id', N'118', 3, N'Rooms'),
        (856, 119, N'string', N'.
2. ', 4, N'Rooms'),
        (857, 119, N'id', N'109', 5, N'Rooms'),
        (858, 119, N'string', N'''s bunk: some cheap plastic gachapon toys, a small potted cactus and a set of dice.
3. ', 6, N'Rooms'),
        (859, 119, N'id', N'110', 7, N'Rooms'),
        (860, 119, N'string', N'''s bunk: small corner, teligious symbol, family photo.
4. ', 8, N'Rooms'),
        (861, 119, N'id', N'111', 9, N'Rooms'),
        (862, 119, N'string', N'''s bunk: cute bedspread, handgun under the pillow with a full clip.
5. ', 10, N'Rooms'),
        (863, 119, N'id', N'112', 11, N'Rooms'),
        (864, 119, N'string', N'''s bunk: Dana’s clothes mixed in with Kantaro’s laundry. Discarded tissues beside the bed have YELLOW GOO on them.
6. ', 12, N'Rooms'),
        (865, 119, N'id', N'113', 13, N'Rooms'),
        (866, 119, N'string', N'''s bunk: cache of snacks badly hidden behind a ceiling tile along with a Stimpak.
7. ', 14, N'Rooms'),
        (867, 119, N'id', N'114', 15, N'Rooms'),
        (868, 119, N'string', N'''s bunk: Narcotics supplied by an obliging cargo ship captain. They’ll share if you’re interested – there’s more behind the
ceiling tiles.
8. ', 16, N'Rooms'),
        (869, 119, N'id', N'115', 17, N'Rooms'),
        (870, 119, N'string', N'''s bunk: pin-up posters and a musky smell.
9. ', 18, N'Rooms'),
        (871, 119, N'id', N'107', 19, N'Rooms'),
        (872, 119, N'string', N'''s bunk: cleaned out. A thorough search reveals a cache behind a ceiling tile: an empty squirt bottle, used for misting
plants, along with a revolver and some ammunition.
10. Recreation room: standard bunk converted for recreation purposes. The bed is more of a couch now, and there’s a games console and a small, portable cassette player-recorder.', 20, N'Rooms'),
        (873, 119, N'string', N'Simple bunks in a series of 10 small, individual rooms. 
The ceiling tiles can be easily removed, should anyone try, to reveal a crawlspace above full of wiring and pipes, with access to the vents.', 0, N'Description'),
        (889, 107, N'string', N'Mike', 0, N'Name'),
        (890, 107, N'string', N'Senior Mining Engineer', 0, N'Position'),
        (891, 107, N'string', N'Yes, to the point of liquefaction', 0, N'Is infected?'),
        (892, 107, N'string', N'Disappeared last night. Nobody knows why, or where he is.', 0, N'Description'),
        (893, 108, N'string', N'Sonya', 0, N'Name'),
        (894, 108, N'string', N'Team Leader', 0, N'Position'),
        (895, 108, N'string', N'No', 0, N'Is infected?'),
        (896, 108, N'string', N'Team leader at the base. 
Wants to find out what’s going on. 
She reported traces of a strange substance found in the mine a couple of months ago, but hasn’t thought much about it since. 
Mike had been acting a little odd since they found it.
Spends most of the time listening to music on her oversized headphones.', 0, N'Description'),
        (897, 109, N'string', N'Ashraf', 0, N'Name'),
        (898, 109, N'string', N'Breaker', 0, N'Position'),
        (899, 109, N'string', N'No', 0, N'Is infected?'),
        (900, 109, N'string', N'Short and stocky, accommodating, naïve', 0, N'Description'),
        (901, 110, N'string', N'Dana', 0, N'Name'),
        (902, 110, N'string', N'Head driller', 0, N'Position'),
        (903, 110, N'string', N'No', 0, N'Is infected?'),
        (904, 110, N'string', N'Stoic, professional, sullen.', 0, N'Description'),
        (905, 111, N'string', N'Jerome', 0, N'Name'),
        (906, 111, N'string', N'Assistant driller', 0, N'Position'),
        (907, 111, N'string', N'No', 0, N'Is infected?'),
        (908, 111, N'string', N'Tall, playful, on edge', 0, N'Description'),
        (909, 112, N'string', N'Kantaro', 0, N'Name'),
        (910, 112, N'string', N'Loader', 0, N'Position'),
        (911, 112, N'string', N'Yes, shows first stages (aversion to water, excessive sweating)', 0, N'Is infected?'),
        (912, 112, N'string', N'Muscular, quiet, hasn’t bathed in a few days, INFECTED', 0, N'Description'),
        (913, 113, N'string', N'Morgan', 0, N'Name'),
        (914, 113, N'string', N'Loader', 0, N'Position'),
        (915, 113, N'string', N'No', 0, N'Is infected?'),
        (916, 113, N'string', N'Laid back, friendly, nervous', 0, N'Description'),
        (917, 114, N'string', N'Rie', 0, N'Name'),
        (918, 114, N'string', N'Putter', 0, N'Position'),
        (919, 114, N'string', N'No', 0, N'Is infected?'),
        (920, 114, N'string', N'Small, sarcastic, impish, drug addict', 0, N'Description'),
        (927, 115, N'string', N'Rosa', 0, N'Name'),
        (928, 115, N'string', N'Junior Mining Engineer', 0, N'Position'),
        (929, 115, N'string', N'No', 0, N'Is infected?'),
        (930, 115, N'string', N'Fit, laconic, domineering.
Believes that ', 0, N'Description'),
        (931, 115, N'id', N'107', 1, N'Description'),
        (932, 115, N'string', N' is incompetent and resents him.', 2, N'Description'),
        (933, 116, N'string', N'Prince', 0, N'Name'),
        (934, 116, N'string', N'Cat', 0, N'Position'),
        (935, 116, N'string', N'No', 0, N'Is infected?'),
        (936, 116, N'string', N'Brought aboard (against regulations) by ', 0, N'Description'),
        (937, 116, N'id', N'113', 1, N'Description'),
        (938, 116, N'string', N'.
Hates baths.
Can see ', 2, N'Description'),
        (939, 116, N'id', N'105', 3, N'Description'),
        (940, 116, N'string', N' and reacts with hissing to its presence.', 4, N'Description'),
        (950, 120, N'string', N'Mess', 0, N'Name'),
        (951, 120, N'string', N'Yes', 0, N'Is pressurised?'),
        (952, 120, N'string', N'Dinning and cooking area', 0, N'Role'),
        (953, 120, N'string', N'Kitchen, small hydroponic garden, main dining area', 0, N'Rooms'),
        (954, 120, N'string', N'Communal eating area. The automated kitchen unit is restocked by the cargo ships that visit each month.
', 0, N'Description'),
        (955, 120, N'id', N'116', 1, N'Description'),
        (956, 120, N'string', N'  has a cardboard box bed here, along with his food and water bowls.
A hydroponic garden connected to the vents, grows fresh salad. A rota is pinned to the wall next to it, with a different crew
member tasked with the garden’s upkeep each month. ', 2, N'Description'),
        (957, 120, N'id', N'107', 3, N'Description'),
        (958, 120, N'string', N' is the last name on the list. The plants are visibly beginning to wilt.', 4, N'Description'),
        (959, 105, N'string', N'The Monster', 0, N'Name'),
        (960, 105, N'string', N'Alien', 0, N'Type'),
        (961, 105, N'string', N'40', 0, N'Hit points'),
        (962, 105, N'string', N'3', 0, N'Wounds'),
        (963, 105, N'string', N'An INVISIBLE alien being that was sleeping in a pod within the meteorite, held in stasis on an interstellar voyage, before the mining disturbed it.
Is source of YELLOW GOO. 
Retreats to unreachable chamber inside depths of MINE after suffering a wound and emerges an hour late with full hit points (but NOT all wounds). ', 0, N'Description'),
        (964, 121, N'string', N'Washrooms', 0, N'Name'),
        (965, 121, N'string', N'Yes', 0, N'Is pressurised?'),
        (966, 121, N'string', N'Washing and laundry area', 0, N'Role'),
        (967, 121, N'string', N'Laundry room, washroom proper', 0, N'Rooms'),
        (968, 121, N'string', N'Showers and toilets in a series of cubicles. 
One shower is out of order – according to the other workers, ', 0, N'Description'),
        (969, 121, N'id', N'107', 1, N'Description'),
        (970, 121, N'string', N'  said he accidentally broke it last night, just before he disappeared. 
There is a large, clunky extractor in the ceiling that filters out steam into the vents. It looks like it could be easily removed.', 2, N'Description'),
        (971, 122, N'string', N'Mine', 0, N'Name'),
        (972, 122, N'string', N'No', 0, N'Is pressurised?'),
        (973, 122, N'string', N'Main nonpressurised work area', 0, N'Role'),
        (974, 122, N'string', N'Elevator, tool shed, generator shed, spare parts storage, ore storage, MINE DEPTHS', 0, N'Rooms'),
        (975, 122, N'string', N'Automated drills excavate metals from thin veins of ore in the black rock walls. Machines'' output is pumped up and sorted in
the ', 0, N'Description'),
        (976, 122, N'id', N'118', 1, N'Description'),
        (977, 122, N'string', N'. Area near elevator is cluttered with different types of mining equipment. 
MINE DEPTHS: a splash of YELLOW GOO on the natural cave walls. An empty vaccsuit, slumped in a heap. The word
“SILENCE” is scorched into the wall with a handheld laser cutter that lays discarded nearby.', 2, N'Description'),
        (983, 117, N'string', N'Docking Bay 2', 0, N'Name'),
        (984, 117, N'string', N'Yes', 0, N'Is pressurised?'),
        (985, 117, N'string', N'Docking bay for large ships, currently holding characters'' ship', 0, N'Role'),
        (986, 117, N'string', N'', 0, N'Rooms'),
        (987, 117, N'string', N'The crew docks here to pick up some cargo en route to a trading satellite. ', 0, N'Description'),
        (993, 124, N'string', N'CSV Heracles', 0, N'Name'),
        (994, 124, N'string', N'Yes', 0, N'Is pressurised?'),
        (995, 124, N'string', N'Small research vessel', 0, N'Role'),
        (996, 124, N'string', N'Washroom, science lab, cargo hold, cockpit, crew quarters', 0, N'Rooms'),
        (997, 124, N'string', N'The interior of the ship is sleek, white, clean. Contains all the usual amenities, but its washroom has been violently destroyed using a crowbar. 
Belongs to ', 0, N'Description'),
        (998, 124, N'id', N'106', 1, N'Description'),
        (999, 123, N'string', N'Docking Bay 1', 0, N'Name'),
        (1000, 123, N'string', N'Yes', 0, N'Is pressurised?'),
        (1001, 123, N'string', N'Docking bay for small ships', 0, N'Role'),
        (1002, 123, N'string', N'', 0, N'Rooms'),
        (1003, 123, N'string', N'Research ship ', 0, N'Description'),
        (1004, 123, N'id', N'124', 1, N'Description'),
        (1005, 123, N'string', N' has been docked here for nearly four weeks. The entrance is protected by a numbered keypad – the code is 0389.', 2, N'Description'),
        (1006, 106, N'string', N'Ethan Giovanni', 0, N'Name'),
        (1007, 106, N'string', N'Infected human', 0, N'Type'),
        (1008, 106, N'string', N'25', 0, N'Hit points'),
        (1009, 106, N'string', N'1', 0, N'Wounds'),
        (1010, 106, N'string', N'Geologist. Arrived a little over a month ago, sent by the Company on business that’s above the miners’ pay grade to know about. 
Has been making frequent trips into the mine with scanners and equipment, but the workers don’t know what he’s been doing.
Hasn’t left his ship since emerging from the mine yesterday, talking about “samples” and a “discovery.”', 0, N'Description'),
        (1011, 125, N'string', N'George', 0, N'Name'),
        (1012, 125, N'string', N'Stefano', 0, N'Surname'),
        (1013, 125, N'string', N'32', 0, N'Age'),
        (1014, 125, N'string', N'Italian cook', 0, N'Occupation'),
        (1015, 125, N'string', N'Regular cook without any hidden connections', 0, N'Description'),
        (1016, 125, N'string', N'Quiet and polite person', 0, N'Character'),
        (1017, 126, N'string', N'Sample location', 0, N'Location'),
        (1018, 126, N'string', N'Sample county', 0, N'Country'),
        (1019, 126, N'string', N'Sample population', 0, N'Population'),
        (1020, 126, N'string', N'Sample powerful ruler', 0, N'Ruler'),
        (1021, 126, N'string', N'Some sample points of interest', 0, N'Points of interest'),
        (1022, 127, N'string', N'Castle Greyskull', 0, N'Name'),
        (1023, 127, N'string', N'Almighty Greyskull', 0, N'Ruler/owner'),
        (1024, 127, N'string', N'Fortress', 0, N'Type'),
        (1025, 127, N'string', N'Huge and ruined castle located somewhere in the ', 0, N'Description'),
        (1026, 127, N'id', N'103', 1, N'Description'),
        (1027, 127, N'string', N', currently occupied by warlord Greyskull and his crew. ', 2, N'Description'),
        (1028, 118, N'string', N'Workspace', 0, N'Name'),
        (1029, 118, N'string', N'Yes', 0, N'Is pressurised?'),
        (1030, 118, N'string', N'Main work area (pressurised)', 0, N'Role'),
        (1031, 118, N'id', N'108', 0, N'Rooms'),
        (1032, 118, N'string', N'''s office, workspace proper, reactor, medical station, airlock', 1, N'Rooms'),
        (1033, 118, N'string', N'Work boots clang and echo. Heavily used but sturdy working gear is stowed in cubbies: overalls, flashlights, short-range radios,
handheld mining tools – 10 sets of each plus 9 vaccsuits on wall hooks. One of the mining tools, a handheld laser cutter, is also
missing. 
Cramped corridors lead to the crews’ ', 0, N'Description'),
        (1034, 118, N'id', N'119', 1, N'Description'),
        (1035, 118, N'string', N'.
AIRLOCK separates workspace from ', 2, N'Description'),
        (1036, 118, N'id', N'122', 3, N'Description'),
        (1037, 118, N'string', N' elevator.', 4, N'Description');