insert into "schema" (id, title, campaign_id, fields)
values  (9, N'Characters', 3, N'Name,Affiliations,Occupation,Description'),
        (10, N'Places', 3, N'Description,Residents'),
        (11, N'NPC', 4, N'Name,Surname,Age,Occupation,Description,Character'),
        (12, N'City', 4, N'Location,Country,Population,Ruler,Points of interest'),
        (25, N'NPC', 11, N'Name,Surname,Age,Occupation,Description,Character'),
        (26, N'City', 11, N'Location,Country,Population,Ruler,Points of interest'),
        (35, N'NPC', 16, N'Name,Surname,Age,Occupation,Description,Character'),
        (36, N'City', 16, N'Location,Country,Population,Ruler,Points of interest'),
        (39, N'adsasddasads', 11, N''),
        (40, N'NPC', 17, N'Name,Surname,Age,Occupation,Description,Character'),
        (41, N'City', 17, N'Location,Country,Population,Ruler,Points of interest'),
        (54, N'NPC', 23, N'Name,Surname,Age,Occupation,Description,Character'),
        (55, N'City', 23, N'Location,Country,Population,Ruler,Points of interest'),
        (56, N'Lecturer', 23, N'Name,Surname,Degree,Courses,Salary'),
        (57, N'Course', 23, N'Name,Year'),
        (58, N'SAMPLE', 23, N''),
        (63, N'City', 26, N'Location,Country,Population,Ruler,Points of interest'),
        (64, N'NPC', 26, N'Name,Surname,Age,Occupation,Description,Character'),
        (65, N'Player Characters', 24, N'Name,Surname,Player,Race,Class,Affilation,Notes'),
        (66, N'NPC', 24, N'Name,Race,Position,Role in campaign,Notes'),
        (67, N'Magical items', 24, N'Name,Rarity,Owner,Description'),
        (68, N'Location', 24, N'Name,Ruler/owner,Type,Description'),
        (69, N'Enemy', 25, N'Name,Type,Hit points,Wounds,Description'),
        (70, N'Miner', 25, N'Name,Position,Is infected?,Description'),
        (71, N'Station section', 25, N'Name,Is pressurised?,Role,Rooms,Description'),
        (72, N'NPC', 27, N'Name,Surname,Age,Occupation,Description,Character'),
        (73, N'City', 27, N'Location,Country,Population,Ruler,Points of interest');