insert into "description_metadata" (id, event_id, value, type, sequence_number)
values  (2, 3, N'The crew goes through the gate.', N'string', 0),
        (3, 4, N'Ellie decides to help the ill triceraptor.', N'string', 0),
        (4, 5, N'Alan, Ian and ', N'string', 0),
        (5, 5, N'10', N'id', 1),
        (6, 5, N' grandchildren decides to go on tour with Jeeps.', N'string', 2),
        (7, 6, N'Rexy attacks the Jeeps.', N'string', 0),
        (8, 7, N'Everyone reunites at the base, while the island struggles with the weather.', N'string', 0),
        (9, 2, N'With a great music theme the heroes visit the ', N'string', 0),
        (10, 2, N'12', N'id', 1),
        (11, 2, N' with a helicopter.', N'string', 2),
        (12, 27, N'After quite night, heroes are woken up by sound of alarm. Barbarian horde approaches!', N'string', 0),
        (13, 28, N'Barbarians try to force the gate of outpost', N'string', 0),
        (16, 30, N'The gate has held, but barbarians have established beachhead on the walls. They must be defeated to secure Outpost', N'string', 0),
        (18, 29, N'Barbarians have forced the gate open. Fight moves to courtyard, guards release their war dogs', N'string', 0),
        (21, 32, N'The outpost is lost. Characters must escort its captain to nearest Imperial Garrison to report about failure and incoming barbarian horde.', N'string', 0),
        (22, 33, N'Leader of Northern Outpost defenders thanks the characters and pays them reward for helping in its defense', N'string', 0),
        (25, 40, N'Players did not take Elizas'' offer and are trying to defeat her and her allies. ', N'string', 0),
        (26, 39, N'Erinyes Eliza presents players with counter offer concerning Smiler''s fate.', N'string', 0),
        (27, 41, N'Players decided to take ', N'string', 0),
        (28, 41, N'93', N'id', 1),
        (29, 41, N''' offer and get rid of Smiler for good together.', N'string', 2),
        (30, 42, N'Players presented Smiler with ', N'string', 0),
        (31, 42, N'93', N'id', 1),
        (32, 42, N'''s and thankful Eladrin escorts them to nearest ferry through Styx. ', N'string', 2),
        (33, 43, N'Players'' must navigate treacherous Avernus Wastes to reach ', N'string', 0),
        (34, 43, N'104', N'id', 1),
        (35, 44, N'Players are teleported to Army Group East Camp by Eliza after they dealt with ', N'string', 0),
        (36, 44, N'94', N'id', 1),
        (38, 45, N'Kirkendolt, veteran of many campaigns, shows players around the Army Group camp. On their way through camp, players meet its leader', N'string', 0),
        (41, 38, N'Smiler the Defiler offers players safe passage through Styx if they handle an Erinyes Bounty Hunter following him. ', N'string', 0),
        (42, 47, N'Players arrive at Ypsilon-14 station and disembark from their ship.', N'string', 0),
        (43, 48, N'Players meet with Sonya which informs them about missing Mike and orders to search for him.', N'string', 0),
        (44, 49, N'Players proceed deeper into Workarea, chatting with workers currently present in it and learning about recent events. ', N'string', 0),
        (45, 50, N'Players'' search for ', N'string', 0),
        (46, 50, N'107', N'id', 1),
        (47, 50, N' by investigating crew quarters, mess and washroom at their leisure. 
When they exhaust all clues in those areas, they hear scream from Workarea. ', N'string', 2),
        (48, 51, N'Players arrive in Workspace to see invisible monster devouring Ria''s body and stunned Ashraf, screaming in the corner. Fight ensues.', N'string', 0),
        (49, 52, N'Players confer with Sonya about situation and Monster. She proposes them to either ask some questions to corporate scientist aboard ', N'string', 0),
        (50, 52, N'124', N'id', 1),
        (51, 52, N' or look for ', N'string', 2),
        (52, 52, N'107', N'id', 3),
        (53, 52, N' in ', N'string', 4),
        (54, 52, N'122', N'id', 5),
        (55, 52, N'.', N'string', 6),
        (57, 54, N'Characters decided to go to the mine and search for Mike inside it. They meet with crew of workers repairing drill damaged by ', N'string', 0),
        (58, 54, N'105', N'id', 1),
        (59, 53, N'Characters decided to check science ship docked to station and managed to get around keypad. Inside they are attacked by infected scientists as soon as they enter ship''s lab.', N'string', 0),
        (60, 55, N'After dealing with ', N'string', 0),
        (61, 55, N'106', N'id', 1),
        (62, 55, N' players can search his ship for any clues ', N'string', 2),
        (63, 56, N'After brief search in mine depths, players find Mike - or rather puddle of YELLOW GOO he changed into alongside his equipment and vaccsuit', N'string', 0),
        (64, 57, N'Players are ambushed by the Monster while returning to elevator. Rosa comes to their aid if she is still alive.', N'string', 0),
        (65, 58, N'Players meet again with Sonya to tell her what they found out in mine/on ship. Terrified woman decides to abandon station and leave on players ship. ', N'string', 0),
        (66, 59, N'Players decide NOT to risk their lives for bunch of miners at the edge of known space. They leave immediately. Little they know that ', N'string', 0),
        (67, 59, N'105', N'id', 1),
        (68, 59, N' hitches a ride on their ship...', N'string', 2),
        (71, 60, N'While everybody aboard station scrambles to get supplies and stuff onto players'' ship, the Monster strikes again.', N'string', 0),
        (72, 61, N'Station crew and players leave the Ypsilon-14 aboard players'' ship and scorch the asteroid surface (and all station sections except for ', N'string', 0),
        (73, 61, N'122', N'id', 1),
        (74, 61, N') with ship''s drive plume. 
Little they know that some of the miners can be infected and ', N'string', 2),
        (75, 61, N'105', N'id', 3),
        (76, 61, N' managed to get onto their ship (if it survived all fights). ', N'string', 4),
        (77, 62, N'Yes.', N'string', 0),
        (78, 31, N'Characters managed to defend the outpost and capture prisoners for interrogation which now begins. ', N'string', 0),
        (79, 68, N'Characters approach the mighty Castle Greyskull in search for its infamous owner. They need to decide how to infiltrate the fortress. ', N'string', 0),
        (80, 69, N'Players decided to infiltrate the castle stealthily via its sewer system - they need to pass through maze of tunnels filled with traps.', N'string', 0),
        (84, 70, N'Players decided to storm the ', N'string', 0),
        (85, 70, N'127', N'id', 1),
        (86, 70, N' openly, wands blazing. First step: taking the main gate. ', N'string', 2),
        (87, 71, N'Players decided to fly over the castle''s walls and reach its roof. Unfortunately for them, castle owner has invested in noticeable air defences in form of two angry vyverns. ', N'string', 0),
        (89, 73, N'Players managed to defeat the vyverns and land on the Outer Keep roof. Or crash land. 
Anyway: now they must face team of infernal assassins which sunbathing session has been interrupted by some pesky adventurers. ', N'string', 0),
        (90, 74, N'Players has reached outer keep of the Castle Greyskull were last of the castle defenders are stationed. They have to fight their way to castle''s owner.', N'string', 0),
        (91, 72, N'Players has managed to storm the Main Gate and now are moving through castle''s courtyard in which defenders are mounting significant resistance. ', N'string', 0),
        (93, 75, N'Players miraculously haven''t alerted Mighty Greyskull about their presence in the fortress and can try to capture him without bloodshed. ', N'string', 0),
        (94, 76, N'Greyskull has been alerted about players presence and fled to dungeons where he plans to make his last stand against invaders. ', N'string', 0),
        (95, 77, N'The Castle Greyskull has fallen. 
It''s defenders lie dead or flee with utmost haste. Players have captured their target and can ask him ALL sorts of questions. ', N'string', 0),
        (96, 78, N'Several hours (at least ten or long rest) after the Greyskull has been captured, interrogated and possibly dispatched a strange cloud starts to approach the Castle. 
Avatar of ', N'string', 0),
        (97, 78, N'97', N'id', 1),
        (98, 78, N' appears on fortress'' main courtyard and demands it summary and unconditional surrender while the cloud turns out to be Warmaster''s personal flying fortress...', N'string', 2);