insert into "event" (id, title, type, status, session_id, display_status)
values  (2, N'Welcome to the jungle', N'normal', N'none', 3, N'shown'),
        (3, N'The Gate', N'normal', N'none', 3, N'shown'),
        (4, N'Help ill triceraptor', N'normal', N'none', 3, N'shown'),
        (5, N'Go on tour', N'normal', N'none', 3, N'shown'),
        (6, N'Rexy breaks out', N'fight', N'none', 3, N'shown'),
        (7, N'Reunite', N'normal', N'none', 3, N'shown'),
        (20, N'asd', N'normal', N'done', 10, N'shown'),
        (21, N'132321321', N'normal', N'none', 10, N'shown'),
        (22, N'13212436263623', N'normal', N'done', 10, N'shown'),
        (23, N'dasdada', N'normal', N'done', 10, N'shown'),
        (24, N'saddsadsaas', N'normal', N'none', 10, N'shown'),
        (25, N'testtesttest', N'normal', N'none', 10, N'shown'),
        (27, N'Barbarians Approach', N'normal', N'none', 12, N'shown'),
        (28, N'Fight For Gate', N'fight', N'none', 12, N'shown'),
        (29, N'Fight in Courtyard', N'fight', N'none', 12, N'shown'),
        (30, N'Fight for Walls', N'fight', N'none', 12, N'shown'),
        (31, N'Outpost Secured', N'normal', N'none', 12, N'shown'),
        (32, N'Outpost Lost', N'normal', N'none', 12, N'shown'),
        (33, N'Outpost Debrifing', N'normal', N'none', 12, N'shown'),
        (34, N'Event 1', N'normal', N'none', 13, N'shown'),
        (35, N'Event 2', N'normal', N'none', 13, N'shown'),
        (36, N'Event 3', N'normal', N'none', 13, N'shown'),
        (37, N'Event 4', N'normal', N'none', 13, N'shown'),
        (38, N'Meeting with Smiler', N'normal', N'done', 15, N'shown'),
        (39, N'Meeting With Eliza', N'normal', N'done', 15, N'shown'),
        (40, N'Fight Against Eliza', N'fight', N'omitted', 15, N'hidden'),
        (41, N'Fight Against Smiler', N'fight', N'none', 15, N'shown'),
        (42, N'Moving through Styx', N'normal', N'none', 15, N'shown'),
        (43, N'Travel to Army Camp', N'normal', N'none', 15, N'shown'),
        (44, N'Teleporation to Army Camp', N'normal', N'none', 15, N'shown'),
        (45, N'Sightseeing', N'normal', N'none', 15, N'shown'),
        (47, N'Ship arrives', N'normal', N'none', 16, N'shown'),
        (48, N'Meeting with Sonya', N'normal', N'none', 16, N'shown'),
        (49, N'Meeting the workers', N'normal', N'none', 16, N'shown'),
        (50, N'Search for Mike', N'normal', N'none', 16, N'shown'),
        (51, N'First fight with Monster', N'fight', N'none', 16, N'shown'),
        (52, N'Second meeting with Sonya', N'normal', N'none', 16, N'shown'),
        (53, N'Fight with Giovanni', N'fight', N'none', 16, N'shown'),
        (54, N'Investigating the mine', N'normal', N'none', 16, N'shown'),
        (55, N'Investigating the Hercules', N'normal', N'none', 16, N'shown'),
        (56, N'Finding Mike', N'normal', N'none', 16, N'shown'),
        (57, N'Second fight with Monster', N'fight', N'none', 16, N'shown'),
        (58, N'Third meeting with Sonya', N'normal', N'none', 16, N'shown'),
        (59, N'Screw this, we are out', N'normal', N'none', 16, N'shown'),
        (60, N'Evacuation ambush', N'fight', N'none', 16, N'shown'),
        (61, N'The End of Ypsilon-14...?', N'normal', N'none', 16, N'shown'),
        (62, N'Everything has a start', N'normal', N'none', 17, N'shown'),
        (63, N'Event 1', N'normal', N'none', 24, N'shown'),
        (64, N'Event 2', N'normal', N'none', 24, N'shown'),
        (65, N'Event 3', N'normal', N'none', 24, N'shown'),
        (67, N'Event 4', N'normal', N'none', 24, N'shown'),
        (68, N'The Approach', N'normal', N'none', 25, N'shown'),
        (69, N'Sewers', N'normal', N'none', 25, N'shown'),
        (70, N'Main Gate', N'fight', N'none', 25, N'shown'),
        (71, N'Walls', N'fight', N'none', 25, N'shown'),
        (72, N'Courtyard', N'fight', N'none', 25, N'shown'),
        (73, N'Roof', N'fight', N'none', 25, N'shown'),
        (74, N'Outer Keep', N'normal', N'none', 25, N'shown'),
        (75, N'Inner Keep', N'normal', N'none', 25, N'shown'),
        (76, N'Dungeons', N'fight', N'none', 25, N'shown'),
        (77, N'Interrogation', N'normal', N'none', 25, N'shown'),
        (78, N'Old Enemy Approaches', N'normal', N'none', 25, N'shown');